## Import the libraries

In [1]:
import numpy as np
import keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense

## Define the source data

In [2]:
# Sample text data
text_data = [
    "hello how are you",
    "hello how have you been",
    "hi there",
    "good morning",
    "good night",
    "have a nice day",
    "how is it going",
    "how have you been",
    "nice to meet you",
    "thank you"
]

## Create the tokenizer

In [3]:
# Prepare the tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_data)
total_words = len(tokenizer.word_index) + 1

In [4]:
total_words

21

In [5]:
tokenizer.word_index

{'you': 1,
 'how': 2,
 'have': 3,
 'hello': 4,
 'been': 5,
 'good': 6,
 'nice': 7,
 'are': 8,
 'hi': 9,
 'there': 10,
 'morning': 11,
 'night': 12,
 'a': 13,
 'day': 14,
 'is': 15,
 'it': 16,
 'going': 17,
 'to': 18,
 'meet': 19,
 'thank': 20}

## Prepare the input sequences

In [6]:
# Create sequences of words
input_sequences = []
for line in text_data:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [7]:
input_sequences

[[4, 2],
 [4, 2, 8],
 [4, 2, 8, 1],
 [4, 2],
 [4, 2, 3],
 [4, 2, 3, 1],
 [4, 2, 3, 1, 5],
 [9, 10],
 [6, 11],
 [6, 12],
 [3, 13],
 [3, 13, 7],
 [3, 13, 7, 14],
 [2, 15],
 [2, 15, 16],
 [2, 15, 16, 17],
 [2, 3],
 [2, 3, 1],
 [2, 3, 1, 5],
 [7, 18],
 [7, 18, 19],
 [7, 18, 19, 1],
 [20, 1]]

## Padding of sequences

In [8]:
max_sequence_len = max([len(x) for x in input_sequences])
input_sequences = pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre')

In [9]:
input_sequences

array([[ 0,  0,  0,  4,  2],
       [ 0,  0,  4,  2,  8],
       [ 0,  4,  2,  8,  1],
       [ 0,  0,  0,  4,  2],
       [ 0,  0,  4,  2,  3],
       [ 0,  4,  2,  3,  1],
       [ 4,  2,  3,  1,  5],
       [ 0,  0,  0,  9, 10],
       [ 0,  0,  0,  6, 11],
       [ 0,  0,  0,  6, 12],
       [ 0,  0,  0,  3, 13],
       [ 0,  0,  3, 13,  7],
       [ 0,  3, 13,  7, 14],
       [ 0,  0,  0,  2, 15],
       [ 0,  0,  2, 15, 16],
       [ 0,  2, 15, 16, 17],
       [ 0,  0,  0,  2,  3],
       [ 0,  0,  2,  3,  1],
       [ 0,  2,  3,  1,  5],
       [ 0,  0,  0,  7, 18],
       [ 0,  0,  7, 18, 19],
       [ 0,  7, 18, 19,  1],
       [ 0,  0,  0, 20,  1]])

In [10]:
input_sequences.shape

(23, 5)

## Split into features and labels 

In [12]:
input_sequences = np.array(input_sequences)
X, y = input_sequences[:,:-1], input_sequences[:,-1]
y = keras.utils.to_categorical(y, num_classes=total_words)

In [13]:
input_sequences[:,-1]

array([ 2,  8,  1,  2,  3,  1,  5, 10, 11, 12, 13,  7, 14, 15, 16, 17,  3,
        1,  5, 18, 19,  1,  1])

In [14]:
y

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0.,

## Build the RNN model 

In [15]:
model = Sequential()
model.add(Embedding(total_words, 10, input_length=max_sequence_len-1))
model.add(LSTM(150, return_sequences=True))
model.add(LSTM(100))
model.add(Dense(total_words, activation='softmax'))

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 10)             210       
                                                                 
 lstm (LSTM)                 (None, 4, 150)            96600     
                                                                 
 lstm_1 (LSTM)               (None, 100)               100400    
                                                                 
 dense (Dense)               (None, 21)                2121      
                                                                 
Total params: 199331 (778.64 KB)
Trainable params: 199331 (778.64 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## Compile the model 

In [17]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

## Train the model 

In [18]:
model.fit(X, y, epochs=200, batch_size=1)

Epoch 1/200


23/23 [==============================] - 4s 9ms/step - loss: 3.0435 - accuracy: 0.1739
Epoch 2/200
23/23 [==============================] - 0s 9ms/step - loss: 2.9959 - accuracy: 0.2174
Epoch 3/200
23/23 [==============================] - 0s 9ms/step - loss: 2.8556 - accuracy: 0.2174
Epoch 4/200
23/23 [==============================] - 0s 9ms/step - loss: 2.7289 - accuracy: 0.2174
Epoch 5/200
23/23 [==============================] - 0s 9ms/step - loss: 2.7083 - accuracy: 0.2174
Epoch 6/200
23/23 [==============================] - 0s 9ms/step - loss: 2.7008 - accuracy: 0.2174
Epoch 7/200
23/23 [==============================] - 0s 10ms/step - loss: 2.6182 - accuracy: 0.2174
Epoch 8/200
23/23 [==============================] - 0s 10ms/step - loss: 2.6081 - accuracy: 0.2174
Epoch 9/200
23/23 [==============================] - 0s 10ms/step - loss: 2.5818 - accuracy: 0.2174
Epoch 10/200
23/23 [==============================] - 0s 10ms/step - loss: 2.5608 - accuracy: 0.2174
Epo

23/23 [==============================] - 0s 10ms/step - loss: 0.2600 - accuracy: 0.8261
Epoch 79/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2661 - accuracy: 0.7391
Epoch 80/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2499 - accuracy: 0.8696
Epoch 81/200
23/23 [==============================] - 0s 9ms/step - loss: 0.2434 - accuracy: 0.8261
Epoch 82/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2390 - accuracy: 0.8261
Epoch 83/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2458 - accuracy: 0.7826
Epoch 84/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2373 - accuracy: 0.8261
Epoch 85/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2340 - accuracy: 0.7826
Epoch 86/200
23/23 [==============================] - 0s 9ms/step - loss: 0.2395 - accuracy: 0.8261
Epoch 87/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2308 - accuracy: 0.8261
Epoch

23/23 [==============================] - 0s 10ms/step - loss: 0.2064 - accuracy: 0.8261
Epoch 160/200
23/23 [==============================] - 0s 9ms/step - loss: 0.2065 - accuracy: 0.7826
Epoch 161/200
23/23 [==============================] - 0s 9ms/step - loss: 0.1917 - accuracy: 0.8261
Epoch 162/200
23/23 [==============================] - 0s 9ms/step - loss: 0.2017 - accuracy: 0.8261
Epoch 163/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2022 - accuracy: 0.8261
Epoch 164/200
23/23 [==============================] - 0s 7ms/step - loss: 0.1997 - accuracy: 0.8696
Epoch 165/200
23/23 [==============================] - 0s 9ms/step - loss: 0.1990 - accuracy: 0.8696
Epoch 166/200
23/23 [==============================] - 0s 10ms/step - loss: 0.1915 - accuracy: 0.8696
Epoch 167/200
23/23 [==============================] - 0s 10ms/step - loss: 0.2026 - accuracy: 0.8261
Epoch 168/200
23/23 [==============================] - 0s 11ms/step - loss: 0.2014 - accuracy: 0.8696

## Prediction on new data

In [23]:
new = 'nice'
def predict_next_word(model, tokenizer, new, max_sequence_len):
    tokenizer = Tokenizer()
    tokenizer.fit_on_texts(new)
    max_sequence_len = max([len(x) for x in input_sequences])
    return model

In [25]:
next_word = predict_next_word(model, tokenizer, new, max_sequence_len)
print(f"Next word: {next_word}")
next_word

Next word: <keras.src.engine.sequential.Sequential object at 0x0000026BD835A890>
